@id = 60d15e94-403e-4c04-87c2-f4596c8ef627

PUT http://localhost:5053/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Test123sa34",
  "description": "testwer",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory":[
    "test12",
    "test234234"
  ],
  "sweet":[
    "test123423"
  ]
}